[package]
name = "strata-asm-common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-manifest-types.workspace = true
strata-asm-types.workspace = true
strata-btc-types.workspace = true
strata-l1-envelope-fmt = { workspace = true, optional = true }
strata-l1-txfmt.workspace = true
strata-merkle.workspace = true
strata-msg-fmt.workspace = true

bitcoin.workspace = true
borsh.workspace = true
rand = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-identifiers.workspace = true
strata-test-utils.workspace = true

[features]
test-utils = ["dep:rand", "dep:strata-l1-envelope-fmt"]
